### ISSUE TITLE
GPS-data opens google maps and not google earth

### ISSUE THREAD

**Issue by mcschnee** [slf-dot-ch/snowmicropyn#3]
Installed on my mac: google earth pro
The click on the link automatically opens google maps in Safari

**Comment by marscho1** [comment]
This is intended. Clicking on the coordinates (link) in the sidebar opens google maps in your browser. This is meant to get a quick view where the profile was recorded. 

In case you want to use Google Earth, open all pnt files you're interested in and the click the "KML" button. A KML file is created containing the locations of all open pnt files. Open this KML file in Google Earth or any other application capable to handle KML files.
