### ISSUE TITLE
replace "distance" by "snow depth" in x-axis, increase font size in plot

### ISSUE THREAD

**Issue by mcschnee** [slf-dot-ch/snowmicropyn#4]
minor comment. Schriftgrösse ist zu klein, um die Plots in Präsentationen 1:1 gut lesen zu können

**Comment by marscho1** [comment]
Thank you for your comment. Potential solution:  Adding a "presentation mode" in *pyngui*.

**Comment by marscho1** [comment]
Fixed in v1.0.0a2: Label of x axis: "Snow Depth [mm]". Increased font of axis labels and tick labels slightly.
