### ISSUE TITLE
Future Warning: The pandas.np module is deprecated

### ISSUE THREAD

**Issue by liellnima** [slf-dot-ch/snowmicropyn#8]
Hi there, 
I am not sure if I am the only one, but I get a deprecation warning when using the snowmicropyn:

"FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead"

As far as I have checked the affected files are the following ones (all in the snowmicropyn dir):

- windowing.py
- tools.py
- proksch2015.py
- profile.py
- loewe2012.py
- detection.py

At the moment I am just surpressing the warnings, but I thought it might be helpful for all users, if this was fixed before it becomes a problem :)

**Comment by reisecker** [comment]
Fixed in 0b2be15, thanks.
